Packer base
Otus-DevOps-2023-07/Hellarin_infra pull request #10
Opened 2023-11-08 02:30 UTC by Hellarin

# Выполнено ДЗ № 5

 - [* ] Основное ДЗ
 - [ ] Задание со *

## В процессе сделано:
 - Пункт 1
 - Пункт 2

## Как запустить проект:
 - Например, запустить команду X в директории Y

## Как проверить работоспособность:
 - Например, перейти по ссылке http://localhost:8080

## PR checklist
 - [ ] Выставил label с номером домашнего задания
 - [ ] Выставил label с темой домашнего задания

2023-11-08 20:17 UTC, mrgreyves requested changes
Здравствуйте!)
Какие то проблемы с packer/ubuntu16.json
Он даже как то странно отображается
Локально у вас все проверки проходят?

2023-11-09 06:47 UTC, Hellarin commented
> Здравствуйте!) Какие то проблемы с packer/ubuntu16.json Он даже как то странно отображается Локально у вас все проверки проходят?

Добрый день, проблема вообще в том что в дз про формат json  вообще не говориться только hcl с которым работает пакер , для чего json не понятно и почему автотесты его требуют тоже не понятно .
я просто перенес hcl в json но видимо что то не так все равно , нужно как то приводить к формату json

2023-12-13 16:39 UTC, mrgreyves commented
Здравствуйте!
Стоит использовать конфигурацию которая приведена в примерах в методичке

2023-12-17 11:34 UTC, mrgreyves commented
Здравствуйте!
У вас там проблемы с json
Кажется что можно быстро поправить

2023-12-25 12:39 UTC, closed without merging